### ISSUE TITLE
User Services ko có hàm check exist như trong States Services ???

### ISSUE THREAD

**Issue by mchoang98** [futureskyprojects/FintechGam#1]
![image](https://user-images.githubusercontent.com/40058856/123665299-5b97c600-d862-11eb-9247-9d5023977315.png)

![image](https://user-images.githubusercontent.com/40058856/123665176-386d1680-d862-11eb-9bb1-e28fe9f4d450.png)

**Comment by mchoang98** [comment]
toPromise() cũng không có 
![image](https://user-images.githubusercontent.com/40058856/123665954-f7293680-d862-11eb-9171-ce2a23eb8b92.png)

**Comment by futureskyprojects** [comment]
![image](https://user-images.githubusercontent.com/40263996/123750064-56795c00-d8e0-11eb-8d68-24e196b89a1a.png)
Đã cập nhật thêm 3 API để kiểm tra theo từng trường.
Với tham biến userID có thể có hoặc không để khi check API né thông tin của người đang truyền ra (Dùng khi update user)

**Comment by futureskyprojects** [comment]
Nếu đã OK thì tiến hành close issuse #1 nhé
